[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npx serve dist -p $PORT -s"

[variables]
NODE_ENV = "production"
VITE_API_URL = "https://turnio-backend-production.up.railway.app" 