[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci --only=production=false"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run serve"

[variables]
NODE_ENV = "production"
VITE_API_URL = "${RAILWAY_PUBLIC_DOMAIN:+https://$RAILWAY_PUBLIC_DOMAIN}" 