[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm']

[phases.install]
cmds = [
    'cd backend',
    'npm ci --only=production',
    'npx prisma generate'
]

[phases.build]
cmds = [
    'cd backend',
    'echo "Build completed"'
]

[start]
cmd = 'cd backend && npm start'

[variables]
NODE_ENV = 'production' 