[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "npx prisma generate",
  "echo 'Prisma client generated successfully'"
]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production" 