[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npx prisma generate"]

[start]
cmd = "npx prisma migrate deploy && npm start"

[variables]
NODE_ENV = "production"
FRONTEND_URL = "https://turnio-frontend-production.up.railway.app" 