[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["npm ci --include=dev"]

[phases.build]
cmds = [
  "npm run build",
  "echo 'Build completed - Prisma client generated'"
]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false" 